---
title: "Basic Alignment"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{basic-alignment}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This is mainly a way to test our code without having a full `testthat` workflow.

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#devtools::document(); devtools::install(quick=T)
library(alto)
library(stringr)
```

This step will eventually be replaced by a `run_lda_models` call.

```{r}
data = matrix(sample(0:1000, size = 24), 4, 6)
lda_varying_params_lists <- lapply(1:5, function(z) list(k = z))
names(lda_varying_params_lists) <- str_c("K", 1:5)
lda_models =
   run_lda_models(
      data = data,
      lda_varying_params_lists = lda_varying_params_lists
      )
```

```{r}
result <- align_topics(lda_models, "consecutive")
result
plot(result)
```

```{r}
library("dplyr")
  result@weights %>%
    group_by(m, k_LDA) %>%
    summarise(topic_weight = sum(weight)) %>%
    group_by(m) %>%
    mutate(
      m_num = match(m, levels(m)),
      ymax = k_LDA / (max(k_LDA) + 1) + cumsum(topic_weight),
      ymin = ymax - topic_weight
    )

```


```{r}
library("tidyr")
library("dplyr")
top_words <- exp(result@models[[n_models(result)]]$beta) %>%
  as_tibble() %>%
  mutate(k_LDA = row_number()) %>%
  pivot_longer(-k_LDA, names_to = "v") %>%
  group_by(k_LDA) %>%
  slice_max(value, n = 2) %>%
  ungroup()

top_words %>%
  mutate(
    m_num = 10,
    ymax = cumsum(value) + 0.1 * row_number() / n(),
    ymin = ymax - value
  )

#    group_by(m, k_LDA) %>%
#    summarise(topic_weight = sum(weight)) %>%
#    group_by(m) %>%
#    mutate(
#      m_num = match(m, levels(m)),
#      ymax = k_LDA / (max(k_LDA) + 1) + cumsum(topic_weight),
#      ymin = ymax - topic_weight
#    )
#}
```


```{r}
result <- align_topics(lda_models, "all")
result
```

```{r}
result <- align_topics(lda_models, "consecutive", method = "transport")
result
```

```{r}
plot(result)
```

