---
title: "lda-simulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{lda-simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
params:
  out_dir: "lda"
  method: "product"
  id: 1
  K: 5
  V: 50
  N: 30
  n_models: 5
  save: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
  )
set.seed(params$id)
```

```{r}
library(MCMCpack)
library(alto)
library(dplyr)
library(ggplot2)
library(purrr)
library(readr)
library(stringr)
source("https://raw.githubusercontent.com/krisrs1128/topic_align/main/simulations/simulation_functions.R")
my_theme()
```

```{r}
attach(params)
lambdas <- list(beta = 0.1, gamma = .5, count = 1e4)
betas <- rdirichlet(K, rep(lambdas$beta, V))
gammas <- rdirichlet(N, rep(lambdas$gamma, K))
x <- simulate_lda(betas, gammas, lambda = lambdas$count)
```


```{r}
lda_params <- map(1:n_models, ~ list(k = .))
names(lda_params) <- str_c("K", 1:n_models)
#alignment <- x %>%
#  run_lda_models(lda_params, reset = TRUE) %>%
#  align_topics(method = params$method)
```

```{r}
lda_models <- x %>%
  run_lda_models(lda_params, reset = TRUE)
```


```{r}
alignment <- align_topics(lda_models, method = params$method)
```

```{r}
plot(alignment)
plot_beta(alignment, c(2, 4))
```

```{r}
stability <- alto:::compute_stability_along_branches(alignment@weights) %>%
  mutate(id = params$id)
ggplot(stability, aes(m, stability)) +
  geom_line(aes(group = branch), alpha = 0.5)
```

```{r}
refinement <- alto:::compute_refinement_scores(alignment@weights) %>%
  filter(m != str_c("K", n_models)) %>%
  mutate(id = params$id)
ggplot(refinement) +
  geom_point(aes(m, refinement_score)) +
  scale_y_log10()
```

```{r}
key_topics <- alto:::compute_number_of_key_topics(alignment@weights, T) %>%
  mutate(id = params$id)
```

```{r}
id_vars <- params[c("out_dir", "method", "id", "N", "V", "K")]
if (params$save) {
  dir.create(params$out_dir, recursive = TRUE)
  write_csv(key_topics, save_str("key_topics", id_vars))
  write_csv(refinement, save_str("refinement", id_vars))
  write_csv(stability, save_str("stability", id_vars))
  exper <- list(x, alignment)
  save(exper, file = save_str("exper", id_vars, "rda"))
}
```
